### ISSUE TITLE
Better movie details design

### ISSUE THREAD

**Issue by Indisparte** [Indisparte/CineMates#128]
Currently the design includes 3 tabs:
- info
- cast
- images

This layout makes the lineup screen very long and messy, allowing you to add more information without weighing down the user interface.

## Todo List
- [ ] Add watch providers, these must be visible through a bottom sheet fragment 
- [ ] Show a film's certification 
- [ ] Show the crew of a movie 
- [ ] Insert a tab to view reviews
- [ ] Improved design for chips like this 

### Alternative
You could take advantage of a tab design so you can find common information between Movies and TV Shows so you can take advantage of the same layout

**Comment by Indisparte** [comment]
- [ ] Add watch providers, these must be visible through a bottom sheet fragment 
- [ ] Show a film's certification 
- [ ] Show the crew of a movie 
- [ ] Insert a tab to view reviews
